services:
  - type: web
    name: amaototyann
    runtime: docker
    plan: free
    envVars:
      - key: IS_RENDER_SERVER
        value: "True"
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
    healthCheckPath: /health
